### ISSUE TITLE
compilation errors

### ISSUE THREAD

**Issue by aaannndddyyy** [polyworld/polyworld#11]
In file included from ./sim/globals.h:21:0,
                 from ./agent/agent.h:23,
                 from utils/objectxsortedlist.h:8,
                 from utils/objectxsortedlist.cc:11:
./utils/AbstractFile.h:4:18: fatal error: zlib.h: No such file or directory
 #include <zlib.h>
                  ^
compilation terminated.

**Comment by tinkerttoy** [comment]
It seems like you've not installed the development packages for zlib. You should do that then try again.

**Comment by aaannndddyyy** [comment]
Following your howto:
sudo apt-get install zlib1g-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zlib1g is already the newest version.


sudo apt-get install git g++ mesa-common-dev libqt4-dev libgsl0-dev libgsl0-dbg
git clone https://github.com/polyworld/polyworld.git
cd polyworld

~/polyworld$ ./configure
Operating System: linux
CXX: g++
Toolchain: gcc
QMake: qmake
Optimization: optimized
Warning! Encountered errors when cleaning build environment!
OpenMP Supported: False
Configure complete.

 make
bash: make: command not found

So I did:
sudo apt-get install build-essential

./configure does not complain anymore
make ends with:

/home/andy/polyworld/.bld/library/agent/AgentAttachedData.o -lGL -lGLU -ldl -lgsl -lgslcblas -lgomp -lz
/usr/bin/ld: /home/andy/polyworld/.bld/library/utils/objectxsortedlist.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/home/andy/polyworld/.bld/library/utils/objectxsortedlist.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [/home/andy/polyworld/lib/libpolyworld.so] Error 1
make[1]: Leaving directory `/home/andy/polyworld/src/library'
make: *** [library] Error 2

**Comment by colinrlly** [comment]
I too got the zlib error. I fixed it using the command: sudo apt-get install --reinstall zlibc zlib1g zlib1g-dev. 

I now have the what seems like a similar error:

/usr/bin/ld: /home/colin/Desktop/polyworld/.bld/library/sim/globals.o: relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/home/colin/Desktop/polyworld/.bld/library/sim/globals.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [/home/colin/Desktop/polyworld/lib/libpolyworld.so] Error 1
make[1]: Leaving directory `/home/colin/Desktop/polyworld/src/library'
make: *** [library] Error 2

**Comment by colinrlly** [comment]
Implementing the solution in issue #9 allowed me to build properly @aaannndddyyy

**Comment by larryy** [comment]
The solution in issue #9 (add -fPIC to CXXFLAGS) is now included in ./configure. Based on colinrlly's comment I'm going to assume this is fixed and close the issue, but if there's still a problem feel free to reopen it.
