### ISSUE TITLE
Memory allocated by 'new[]' should be deallocated by 'delete[]', not  delete

### ISSUE THREAD

**Issue by 360CodeSafe** [polyworld/polyworld#15]
1. /src/library/utils/misc.cc line 115

char* itoa(long i)
{
    char* b = new char[256];
    sprintf(b,"%ld", i);
    char* a = new char[strlen(b)+1];
    strcpy(a, b);
    delete b;  //  ->delete[] b;
    return a;
}

2. /src/library/utils/misc.cc line 126

char* ftoa(float f)
{
    char* b = new char[256];
    sprintf(b,"%g", f);
    char* a = new char[strlen(b)+1];
    strcpy(a ,b);
    delete b;  //->delete[] b;
    return a;
}

**Comment by larryy** [comment]
Thanks. Fixed with commit #af5b320
