### ISSUE TITLE
make not successful (ChartMonitorView.cc: undefined reference to `__cxa_throw_bad_array_new_length')

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [polyworld/polyworld#7]
make stops with:

./polyworld/src/app/ui/gui/ChartMonitorView.cc:75: undefined reference to `__cxa_throw_bad_array_new_length'
../../.bld/app/ChartMonitorView.o: In function`ChartMonitorView::addPoint(short, float)':
./polyworld/src/app/ui/gui/ChartMonitorView.cc:320: undefined reference to `__cxa_throw_bad_array_new_length'
../../.bld/app/ChartMonitorView.o: In function`ChartMonitorView::load(std::istream&)':
./polyworld/src/app/ui/gui/ChartMonitorView.cc:367: undefined reference to `__cxa_throw_bad_array_new_length'
./polyworld/lib/libpolyworld.so: undefined reference to`std::__throw_out_of_range_fmt(char const*, ...)@GLIBCXX_3.4.20'
./polyworld/lib/libpolyworld.so: undefined reference to `__cxa_throw_bad_array_new_length@CXXABI_1.3.8'
./polyworld/lib/libpolyworld.so: undefined reference to`std::thread::hardware_concurrency()@GLIBCXX_3.4.17'

Polyworld (with last commit 44ae1ce9003e147b18c098dc011fe8da66f100a8)
gcc 4.9.2
Qt 4.8.6 development files
GSL 1.15
python 2.7.5

further info here (1):
nothing more done.

(1) http://skilledtests.com/wiki/Polyworld

**Comment by meZee** [comment]
I'm unaffected running

gcc 4.9.2 20150304
Qt 4.8.6-5
GSL 1.16-1
python 2.7.9-1
glibc 2.21-2
Archlinux(x86_64)

Looks like it may be related to the glibc versions.

**Comment by larryy** [comment]
As far as I know everything is working currently, and that link took me to a page that wanted me to replace my Flash software with what is almost certainly a trojan, so I am going to close this.
