### ISSUE TITLE
error compiling position independent shared object code

### ISSUE THREAD

**Issue by meZee** [polyworld/polyworld#9]
``` Makefile
/usr/bin/ld: /home/mezee/Development/polyworld-master/.bld/library/graphics/gcamera.o: 
relocation R_X86_64_32S against `_ZTV4gbox' can not be used when making a shared
object; recompile with -fPIC
```

I was able to get around this by executing 

``` shell
export CXXFLAGS=-fpic # Platform dependent(faster)
```

or 

``` shell
export CXXFLAGS=-fPIC # Always works(slower)
```

before running

```
./configure
```

I'm not sure if this is ideal, as it mentions a performance degradation [here](http://www.akkadia.org/drepper/dsohowto.pdf) in regards to those two options.

**Comment by jggiles** [comment]
'export CXXFLAGS=-fPIC' worked for me on Mint. Thanks!

**Comment by gogobebe2** [comment]
Ew, Mint. Get a real distro mate xD

**Comment by larryy** [comment]
Added -fPIC to CXXFLAGS in ./configure. Thanks.
